### ISSUE TITLE
Modular fbcon support.

### ISSUE THREAD

**Issue by cheako** [ilia-glushchenko/VulkanCompositor#2]
I've started working on a rewrite that focuses on implementing support for multiple builds.

1. GLFW build that uses imgui to draw window decorations.  This is the main focus currently.
2. GLFW build that uses a theme-able lua language to draw window decorations, manage window switching, ect.  This will likely not work for some time... if at all.
3. Linux fbcon, with imgui.
4. Linux fbcon, with lua.

Not only is surface creation/management different but input handling also needs to be modular.  The API for input should be a message queue containing libinput biased messages.  GLFW input handlers should post messages after converting then to a format that more closely resembles libinput events.

https://github.com/cheako/vkwayland
This is my first time using cpp and my first time using cmake.  I actively use free software and don't have access to windows or binary video drivers.

Updated git repo 10/26 9PM CST.

**Comment by ilia-glushchenko** [comment]
Consider forking. Otherwise I don't see how this particular issue related to the repository.

**Comment by cheako** [comment]
I've moved my code off of Microsoft's platform to here https://bitbucket.org/cheako/vkwayland/src/master/
